[package]
name = "alphazero_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.16.0", features = ["cuda-jit"] }
bincode = "=2.0.0-rc.3"
bincode_derive = "=2.0.0-rc.3"
rand = "0.9.0"
