[package]
name = "alphazero"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.17.1", features = ["cuda"] }
connect4-lib = "0.1.0"
env_logger = "0.11.8"
log = "0.4.27"
ndarray = "0.16.1"
rand = "0.9.2"
