[package]
name = "alphazero"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.17.0", features = ["cuda"] }
env_logger = "0.11.8"
log = "0.4.27"
rand = "0.9.0"
rchess = "2.3.0"
